### ISSUE TITLE
Cannot read property 'origin' of undefined

### ISSUE THREAD

**Issue by m-merola** [kartik-v/yii2-sortable-input#13]
## Prerequisites

- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] The issue still exists against the latest `master` branch of yii2-sortable-input.
- [ ] This is not an usage question. I confirm having gone through and read the [documentation and demos](http://demos.krajee.com/sortable-input).
- [ ] This is not a general programming / coding question. (Those should be directed to the [webtips Q & A forum](http://webtips.krajee.com/questions)).
- [ ] I have attempted to find the simplest possible steps to reproduce the issue.
- [ ] I have included a failing test as a pull request (Optional).

## Steps to reproduce the issue

1.
2.
3.

## Expected behavior and actual behavior

When I follow those steps, I see...

I was expecting...

#### Browsers

- [X] Google Chrome
- [ ] Mozilla Firefox
- [ ] Internet Explorer
- [ ] Safari

#### Operating System

- [X] Windows
- [ ] Mac OS X
- [ ] Linux
- [ ] Mobile

#### Libraries

- jQuery version: 3.2.1
- yii2-sortable-input version: 1..1

## Isolating the problem

- [ ] This bug happens [on the docs and demos page](https://demos.krajee.com/sortable-input)
- [ ] The bug happens consistently across all tested browsers
- [ ] This bug happens when using yii2-sortable-input without other plugins.

**Comment by krystian-dev548** [comment]
I've got the same problem with the installation of SortableInput on my Yii2:

![capture](https://user-images.githubusercontent.com/24765669/44946170-3c009a80-adf7-11e8-8a4c-13e3456ee3ac.PNG)

**Comment by crimson-med** [comment]
Same problem here.
@m-merola and @Krystian95 I have changed back to `1.1.0` and this solves the issue while awaiting a fix.

**Comment by kartik-v** [comment]
You need to update packages via composer to latest release. You need to have the latest release of dependent yii2-sortable extension.

**Comment by lioPixiumDigital** [comment]
following @crimson-med's comment:
got it all to latest fresh out of the oven version
```json
        "kartik-v/yii2-krajee-base": "dev-master",
        "kartik-v/yii2-sortable": "dev-master",
        "kartik-v/yii2-sortable-input": "dev-master",
```
and yet:
after
```sh
composer update
```
I get 
![screen shot 2018-09-04 at 13 14 07](https://user-images.githubusercontent.com/33018566/45011362-a6f2e100-b044-11e8-8713-b514c3727681.png)
