### ISSUE TITLE
Javascript Error: attr undefined

### ISSUE THREAD

**Issue by Shulmey** [kartik-v/yii2-sortable-input#2]
Here is my code snippet (taken straight from the doc page, changing the field name to match my model):

echo $form->field($model, 'order')->widget(SortableInput::classname(), [
        'items' => [
            1 => ['content' => 'Item # 1'],
            2 => ['content' => 'Item # 2'],
            3 => ['content' => 'Item # 3'],
            4 => ['content' => 'Item # 4'],
            5 => ['content' => 'Item # 5'],
        ],
        'hideInput' => false,
        'options' => ['class'=>'form-control', 'readonly'=>true]
    ]);

I get the following error in my JS console:

Uncaught TypeError: Cannot read property 'attr' of undefined

on line 34 of kv-sortable-input.js:

var $parent = ui.startparent, parentId = $parent.attr('id');

**Comment by kartik-v** [comment]
Cannot replicate this. You can [cross check with the demo page](http://demos.krajee.com/sortable-input).

It seems you have some wrong version or incomplete install. You may want to check if you have the latest updated files of both the `yii2-sortable` and `yii2-sortable-input` extensions by cross checking with the project here on github.

**Comment by Shulmey** [comment]
I downgraded to version 1.1.\* and now it works.  Thanks.

**Comment by kartik-v** [comment]
The latest release works great as well (which you can cross check in demos). You probably may have had some issues with incomplete install or some files getting overwritten.

**Comment by kartik-v** [comment]
The latest release works great as well (which you can cross check in demos). You probably may have had some issues with incomplete install or some files getting overwritten (either manually or somehow).

Also note that you need to update via composer (hope you are not manually copying extension) for ensuring you have correct updated dependencies. For example, this extension depends on yii2-sortable and you need to have the latest version of that which should happen automatically if you use composer.

**Comment by cestal** [comment]
I'm also having this issue using scenario 5 demo code. I'm currently using the latest version. Haven't tried downgrading yet.

**Comment by atiberius** [comment]
I had the same problem. I added "kartik-v/yii2-sortable": "*" to composer.json, which installed also the original yii2-sortable extension and fixed the problem.
It might be that the yii-sortable-input doesn't work installed alone, but together with yii2-sortable.

**Comment by aginanjar** [comment]
Actually I had the same problem after installing`"kartik-v/yii2-sortable-input": "dev-master"` 
Regarding by @Shulmey, its downgrading to version `1.1.*`, then its works now.  

Thank you.
