### ISSUE TITLE
Connected sortables 

### ISSUE THREAD

**Issue by elim051** [kartik-v/yii2-sortable-input#5]
I have a little problem with this widget. Ex I have two lists (ONE and TWO) and only one element XYZ. When I drag XYZ from list A and drop it on list TWO i have in two inputs "1". In second input value was correctly changed, but in first wasn't and i have still "1" there.

**Comment by xushaun** [comment]
I have the same problem use in modal
when I switch to  master branch，problem fixed；
use      composer "kartik-v/yii2-sortable-input": "dev-master"
not    composer "kartik-v/yii2-sortable-input": "*",

**Comment by luigi370** [comment]
Hi there! i got the same problem and this fix, didn't work for me. Any idea? someone? thanks!

**Comment by kartik-v** [comment]
Cannot reproduce. Update your extension to the latest release  and then if an issue exists - update with how you are setting the widget and the issue faced and will reopen this.
