### ISSUE TITLE
Connected sortable inputs - Add / Remove all

### ISSUE THREAD

**Issue by cluwong** [kartik-v/yii2-sortable-input#9]
I have 2 connected sortable inputs which I want to add and remove all from one to the other. I went through the documents and can't find such options / function.
Can this be done at widget level or it's to do with the html5sortable jQuery plugin?

**Comment by kartik-v** [comment]
Did you check the [last example in the usage section of sortable input docs](http://demos.krajee.com/sortable-input#usage)?

You can drag elements from one sortable input to the other and drag all.

I am not clear when you say add remove all? That is not a drag and drop feature - adding and removing all  - can be handled with plain server code... where you eliminate IDs from the SOURCE INPUT and append them to the TARGET INPUT and render your inputs afresh.

**Comment by cluwong** [comment]
Yes, I'm following that example, but added 2 buttons, so that it automatically add all item to one list (and remove all from 2nd list) or remove all from this list (and put them all back to 2nd list) without drag and drop. 

I have tried to do with your suggestion. I have no problem setting data in the hidden input. However the Sortable Input would not refresh / update to reflect such change.

**Comment by kartik-v** [comment]
How do you expect it to refresh by just setting hidden input value? Refresh page or redirect to generate and render widget again with new value from server.

**Comment by CtrlShiftN** [comment]
Also what I want to do if I can not undo/revert the last change  [#19](https://github.com/kartik-v/yii2-sortable-input/issues/19)
